host: localhost:8000
info:
  contact: {}
  description: This is a sample api app
  title: Task API
  version: "2.0"
paths:
  /addTask:
    post:
      consumes:
      - application/json
      description: adds a task, a task object is required in the body.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: add a task
      tags:
      - POST
  /deleteTask:
    delete:
      description: Delete any task by an id parameter
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Delete a task by Id
      tags:
      - DELETE
  /tasks:
    get:
      description: returns task list in json format
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get List of Tasks
      tags:
      - GET
  /updateTask:
    put:
      description: Update any task by providing a new Task in the body and an id in
        the parameters
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Update a task by Id
      tags:
      - PUT
swagger: "2.0"
